### ISSUE TITLE
Impelement changes for mySociety experiment

### ISSUE THREAD

**Issue by equivalentideas** [openaustralia/openaustralia#572]
Here's the description from Rebecca about what's meant to happen for citizens:

> Users of the website would be split into two randomly assigned groups:

> Group 1 would receive a pop up window after 10 seconds of looking at an 'information' page (a page that either displays details of an individual politician, information on legislation or information on the parliament). 

> This pop up will have one question 'Do you know what would you like to do with this information?' with the following answers 

> * 'I'm not sure - click here for suggestions on what to do next' *this takes the user to a page where suggestions for how to use the information they have looked at.
> * 'I'm going to write to an MP'
> * 'I'm going to share this information on social media'
> * 'I'm going to use this information for work purposes'
> * 'I don't need to do anything with this information - I was just browsing'

> Group 2 would not receive a pop-up, but would have access to a tab appearing on the menu-bar that says 'click here for suggestions on what to do next'. This takes the user to the same page as Group 1 accessed where there are  suggestions for how to use the information they have looked at.

The implementation components from @jacksonj04 :

* [x] Add a static page with ‘where next’ content — “There needs to be a single, static page with your “where next” content, similar to the ones Rebecca posted for TheyWorkForYou.”
* [x] add 'where next link to people and debate pages and modal (need more clarification on this) — “The pages where you present relevant content to people (we only present this content on pages about people, and pages containing speeches) need to have a “where next” link added, hidden by default (the ‘group 2’ link), as well as a modal dialog (the ‘group 1’ link).” ([Nick's implementation of link](https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/templates/html/mp/profile.php#L32))
* [x] add mysoc js “You then add our JavaScript, as well as any necessary dependencies (we need jQuery, your modal dialog will probably need some too) to those pages. In theory, if all the elements on the page have been named correctly, the JavaScript will then handle all the work of selecting treatment groups, presenting the appropriate content, and reporting back the results to us (asynchronously, so nothing is slowed down).”

Also, some of the views stuff in Nick's commits on TheyWorkForYou could be useful https://github.com/mysociety/theyworkforyou/commit/5008067c5bb66aef03bb65767b535ac886297b02

**Comment by jacksonj04** [comment]
@equivalentideas - I've just ironed out the show-stopping glitch in our data collector, which means you can now go ahead and get this done (hooray!). Here are some pointers with how we did it on TWFY:

### JavaScript

The JS we use on TheyWorkForYou is at https://github.com/mysociety/theyworkforyou/blob/master/www/docs/js/quant2.js, and it'll do the heavy lifting for you with very minimal changes. It does require jQuery, in order to preserve sanity when editing, but if you're already using that on your site it should be fine. It also needs the Storage API plugin to be loaded before the script (https://github.com/mysociety/theyworkforyou/blob/master/www/docs/js/jquery.storageapi.min.js), to store which bucket people are in without resorting to cookies.

You'll need to modify the `siteTag` on line 4 to something like "openaustralia", but the rest should be able to be left alone with the exception of the methods to open and close the modal dialog (more below).

This only needs to be included on pages which are actively taking part, in this case pages for people and speeches. What we did was put loading the JS into a single file along with the modal dialog content, and then included that toward the bottom of our people and speech pages.

### Static "where next" Page

You can see ours at https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/templates/html/action/where-next.php - as you can tell, it doesn't do anything fancy except record outbound links (which you can do if you want, but we're not collecting that data so it'll be for your own interest). It just needs to be accessible via a URL.

### "Where Next" links

These come on the people and speech pages, and have two variants depending on which bucket a user is sorted into. The choosing of the bucket, unhiding links, showing modal dialogs and recording the outcome is all handled by the JS.

#### Navigation Link

Pretty easy, you can see ours at https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/templates/html/mp/profile.php#L33 and https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/templates/html/section/section.php#L22. As long as the links are `hidden` by default and have an `id="research-quant2-bucket2"` attribute you can put them wherever in your layout and style them however makes most sense to you.

#### Modal Dialog

We have a modal dialog embedded into our person and speech pages (https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/templates/research/quant2.php), which uses our design framework's modals. You can do this using your own if you already have one, or any of the modal libraries out there (http://flaviusmatis.github.io/easyModal.js/ is a good one). Links in this dialog should include one to the static page, with `id="research-quant2-bucket1-wherenext"`. The rest should include `data-research-quant2-bucket1-linkname="foo"`, replacing `foo` with a short descriptor. As long as the `id` and `data-research-quant2-bucket1-linkname` attributes are right the JavaScript will do the magic of recording data and then sending the user on.

The modal dialog is opened using the JS on line https://github.com/mysociety/theyworkforyou/blob/master/www/docs/js/quant2.js#L99, and subsequently closed on https://github.com/mysociety/theyworkforyou/blob/master/www/docs/js/quant2.js#L86. These can be replaced with whichever methods open and close your own modal.
