### ISSUE TITLE
New Member for Wentworth

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/openaustralia#653]
https://www.aph.gov.au/Senators_and_Members/Parliamentarian_Search_Results?q=&ele=Wentworth

**Comment by jamezpolley** [comment]
@MicaelaMicaela  Just letting you know that this seems to be ready to go. Feel free to jump in if you get to this before I do :)

**Comment by MicaelaMicaela** [comment]
APH still hasn't given us a starting date for Phelps (her page is mostly blank)... The AEC declared her as MP for Wentworth on 4 Nov, but she claimed victory back on 20 Oct, and Sharma conceded then too...

I suppose it's much for muchness whichever date we choose to use, so I'm going to go with the earlier 20 Oct 2018 date, since it was the day of the by-election and it appears that the delay on the part of AEC was more bureaucratic paper-shuffling than anything else.

I'll make this change now.

**Comment by MicaelaMicaela** [comment]
haha! wait! looks like you've already done it! all good then :-P
