### ISSUE TITLE
OpenAustralia Voting record does not match with TheyVoteForYou.

### ISSUE THREAD

**Issue by cofiem** [openaustralia/openaustralia#686]
For example:

On [OpenAustralia](https://www.openaustralia.org.au/senator/jacqui_lambie/tasmania): `Voted consistently against	increasing support for the Australian film and TV industry.`

On [TheyVoteForYou](https://theyvoteforyou.org.au/people/senate/tasmania/jacqui_lambie/policies/261): `We can't say anything concrete about how Jacqui Lambie voted on increasing support for the Australian film and TV industry`

**Comment by katska** [comment]
@cofiem thank you for spotting this problem. For the moment we're going to point directly to the voting record on theyvoteforyou. see  https://github.com/openaustralia/publicwhip/issues/1385 
I believe this should be a temporary measure until we can create a better process to draw the voting record into openaustralia.org.au so that it's always up to date. But unfortunately I can't say when we'll be able to do that.
@cofiem is this a satisfactory workaround for the time being?

**Comment by cofiem** [comment]
Yes, I think it makes sense to not duplicate the voting record information.
